[tool.poetry]
name = "molecule-demo-monorepo"
version = "0.1.0"
description = ""
authors = ["Jasstkn <jasssstkn@yahoo.com>"]

[tool.poetry.dependencies]
python = "^2.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
