---
name: Ansible role test

on:
  push:
  pull_request:
    types: ["opened"]

jobs:
  lint:
    name: molecule lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.2
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: poetry install

      # - name: Install dependencies
      #   run: |
      #     pip install ansible==2.9.1 ansible-lint molecule molecule-docker flake8 pytest pytest-testinfra
      - name: Molecule test
        run: |
          source $VENV
          echo $MOLECULE_DISTRO && molecule test -s lint
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ubuntu2004

  molecule-test:
    name: molecule test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2004
          - ubuntu1804
        scenario:
          - oh-my-zsh
      fail-fast: false
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        # to checkout submodules
        with:
          submodules: recursive

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.2
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: poetry install
      - name: Molecule test
        run: |
          source $VENV
          echo $MOLECULE_DISTRO && molecule test -s $MOLECULE_SCENARIO
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_SCENARIO: ${{ matrix.scenario }}
